### ISSUE TITLE
null latitude results in a lot of stacktrace log spam

### ISSUE THREAD

**Issue by mairas** [tkurki/signalk-to-influxdb2#28]
I have a GNSS receiver on the Pi with the antenna suboptimally inside the cabin. The receiver often loses its location fix and reports `null` as navigation.position latitude and longitude. This then results in this stack trace being output every second:

```
Sep 17 11:59:21 openplotter signalk-server[207620]: Error: invalid float value for field 'lat': null
Sep 17 11:59:21 openplotter signalk-server[207620]:     at me.floatField (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:4:3366)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at toPoint (/home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/influx.js:152:15)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at SKInflux.handleValue (/home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/influx.js:119:25)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at /home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:49:57
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Array.forEach (<anonymous>)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at /home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:48:48
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Array.forEach (<anonymous>)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at /home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:47:47
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Array.forEach (<anonymous>)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at FullSignalK.<anonymous> (/home/pi/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:45:39)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at FullSignalK.emit (node:events:525:35)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Function.Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:223:38)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:59:17)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Simple.emit (node:events:525:35)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at addChunk (node:internal/streams/readable:315:12)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at readableAddChunk (node:internal/streams/readable:289:9)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Simple.Readable.push (node:internal/streams/readable:228:10)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Simple._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:122:8)
Sep 17 11:59:21 openplotter signalk-server[207620]:     at Simple.Transform._write (node:internal/streams/transform:205:23)
```

This amounts to hundreds of megabytes of syslog spam every day, filling the poor little disk up unbearably fast. Oh, and it seems the spam is duplicated in /var/log/daemon as well. :-o

Platform: OpenPlotter current-ish updates
Signal K server: 2.2.0
signalk-to-influxdb2: 1.3.4

**Comment by tkurki** [comment]
https://stackoverflow.com/a/118154 😓

**Comment by mairas** [comment]
> https://stackoverflow.com/a/118154 😓

To me, isNaN would only test for NaN values, not for something being a number. I had to think for a bit until I realized that the function name could indeed be interpreted differently, too.

Anyways, thanks for the fix!
