### ISSUE TITLE
Issues with 1.9.2 update

### ISSUE THREAD

**Issue by loganrenz** [tkurki/signalk-to-influxdb2#74]
TypeError: (0 , server_api_1.hasValues) is not a function
    at /home/node/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:99:56

at FullSignalK.onDelta (/home/node/.signalk/node_modules/signalk-to-influxdb2/dist/plugin.js:98:39)
at FullSignalK.emit (node:events:531:35)
at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8)

**Comment by loganrenz** [comment]
Hmmm. No, I was running 2.12.0

**Comment by tkurki** [comment]
Sorry, my mistake in the latest version, fix on the way.

**Comment by loganrenz** [comment]
Thanks, updated and is working now.
