### ISSUE TITLE
No Names Stored for Other Vessels 

### ISSUE THREAD

**Issue by loganrenz** [tkurki/signalk-to-influxdb2#76]
I'm looking back through my data trying to show other ships on a map at a time when I was there. I can find the other ships, and information about them, but I can't find anywhere that the name of the ship is being stored. 

The only errors I am seeing are related to the callsign

Dec 22 04:31:21 TypeError: Cannot create property 'meta' on string 'WDN8779' at /usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:224:35 at Array.reduce (<anonymous>) at addValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:216:27) at addValues (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:188:5) at FullSignalK.addUpdate (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:110:5) at FullSignalK.addUpdates (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:97:10) at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:54:8) at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18) at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21) at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:233:38) at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:83:17) at Simple.emit (node:events:531:35) at addChunk (node:internal/streams/readable:559:12) at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3) at Readable.push (node:internal/streams/readable:391:5) a

**Comment by loganrenz** [comment]
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/23a21f03-99b1-4585-be34-41bc8dabac68" />

I do see a lot of measurements that are empty and the value is [object Object]

**Comment by tkurki** [comment]
Those values without path / _measurement have most probably the vessel names. You'd need parse the objects as JSON and then dig out the name of the vessel from that structure. Doable, but not very straightforward.

I don't think the error message is related in any way to this.

**Comment by tkurki** [comment]
This is something that we could add to the History API: an explicit endpoint to retrieve vessels' static  (like their name) and semi static (like their destination) data.

**Comment by loganrenz** [comment]
`import "strings"
import "experimental/json"

from(bucket: "Tideye")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "<empty>")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["source"] == "ydg-nmea-2000.2")
  // Only keep rows whose _value begins with '{' or '['
  |> filter(fn: (r) =>
    strings.hasPrefix(v: r._value, prefix: "{")
  )
    |> map(fn: (r) => {
      parsed = json.parse(data: bytes(v: r._value))
      return {
        context: r.context,
        _time:  r._time,
        mmsi:   parsed.mmsi,           // May be null if this row doesn't have mmsi
        name:   parsed.name            // May be null if this row doesn't have name
      }
  })
    |> group(columns: ["context"])
      |> reduce(
      identity: {context: "", mmsi: "", name: ""},
    fn: (r, accumulator) => ({
        context: r.context,
        mmsi: if exists r.mmsi and r.mmsi != "" then r.mmsi else accumulator.mmsi,
        name: if exists r.name and r.name != "" then r.name else accumulator.name
    })
  )
  |>group()
  |>yield(name: "named_vessels")`

here's a way I was able to pull out the names of the vessels
